// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
			int n = Integer.parseInt(args[0]);
			int count = 0;
			double greaterThan = 0;
			double lessThan = 0;
	
			while (count < n){
				double random = Math.random();	
				count ++;
				
				if (random > 0.5){
					greaterThan++ ; 
				}
				else {
					lessThan++ ;
				}
			}
	
				double ratio = lessThan/greaterThan;
				if (ratio == 0) {
	
					System.out.println( "> 0.5: "  + (int)greaterThan + " times");
					System.out.println( "<= 0.5: "  + (int)lessThan + " times");
	
				}
	
				else {
	
				System.out.println( "> 0.5: "  + (int)greaterThan + " times");
				System.out.println( "<= 0.5: "  + (int)lessThan + " times");
				System.out.println( "Ratio: "  + ratio);
				}
				
			
		}
	}
	
